[package]
name = "todl"
description = "Tool for finding comment tags in source code"
version = "0.1.4"
edition = "2021"
rust-version = "1.65"
license = "MIT"
repository = "https://github.com/RuairidhWilliamson/todl"
exclude = [
    "temp"
]

[dependencies]
walkdir = "2"
regex = "1"
git2 = { version = "0.16" }
lazy_static = "1.4"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
crossterm = "0.26"
atty = "0.2.14"
unicode-segmentation = "1.10.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "search"
harness = false
