[package]
name = "todl"
description = "Tool for finding comment tags in source code"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
license = "MIT"
repository = "https://github.com/RuairidhWilliamson/todl"
exclude = [
    "temp"
]

[dependencies]
walkdir = "2"
regex = "1"
git2 = "0.15"
lazy_static = "1.4"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "search"
harness = false
